### ISSUE TITLE
"There were errors when initializing the mods"

### ISSUE THREAD

**Issue by firenagy** [EvaisaDev/noita-online#8]
I could play this game mode with my friends normally until recently, the only notable difference being me having factory reset my computer.

Logger text

> Noita (Aug 29 2023) - 20231208-205459
> -------------------------------------------
> Lua (DoFile) error at 'mods/evaisa.mp/init.lua': error loading module 'noitapatcher' from file './mods/evaisa.mp/bin/noitapatcher.dll':
> 	The specified module could not be found.

I have already tried all the solutions to the same error message posted onto the Noita Together github

Any help solving this would be greatly appreciated.

**Comment by dextercd** [comment]
Can you check if the file exists in the path you see there?

If it doesn't exist, then it's probably your anti-virus that ate the file.

If it does exist, then you may be missing a dependency. Try installing the VC++ redistributables from there: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022 you want the x86 version.

**Comment by firenagy** [comment]
The file does exist, I had downloaded vc redist before but I had gotten the x64 version instead of the x86. This seems to have completely solved the problem, thank you for the help!

**Comment by itc1205** [comment]
Hi, could you please update description with noitapatcher requires vc redist x86?
I think that a lot of people would be confused with this error, thanks in advance!

**Comment by EvaisaDev** [comment]
> Hi, could you please update description with noitapatcher requires vc redist x86? I think that a lot of people would be confused with this error, thanks in advance!

The mod should give a popup to download it when you try to launch without it.
